/*
 * File: DataRetriever.java
 *
 * DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS HEADER.
 *
 * The contents of this file are subject to the terms and conditions of 
 * the Common Development and Distribution License 1.0 (the "License").
 *
 * You may not use this file except in compliance with the License.
 *
 * You can obtain a copy of the License by consulting the LICENSE.txt file
 * distributed with this file, or by consulting https://oss.oracle.com/licenses/CDDL
 *
 * See the License for the specific language governing permissions
 * and limitations under the License.
 *
 * When distributing the software, include this License Header Notice in each
 * file and include the License file LICENSE.txt.
 *
 * MODIFICATIONS:
 * If applicable, add the following below the License Header, with the fields
 * enclosed by brackets [] replaced by your own identifying information:
 * "Portions Copyright [year] [name of copyright owner]"
 */

package com.sun.tools.visualvm.modules.coherence.tablemodel.model;

import com.sun.tools.visualvm.modules.coherence.VisualVMModel;

import java.util.List;
import java.util.Map;
import java.util.SortedMap;

import javax.management.MBeanServerConnection;

import javax.management.openmbean.TabularData;

/**
 * Defines the methods for retrieving JMX data from an MBean server.
 *
 * @author Tim Middleton
 */
public interface DataRetriever
{
    /**
     * Return the report to run to collect the data.
     *
     * @return the report to run to collect the data
     */
    public String getReporterReport();


    /**
     * Return a {@link List} of statistics using standard JMX queries
     *
     * @param server the {@link MBeanServerConnection} to use to query
     *
     * @return a {@link List} of statistics collected
     */
    public List<Map.Entry<Object, Data>> getJMXData(MBeanServerConnection server,
                                                    VisualVMModel         model);


    /**
     * Return a {@link List} of statistics given a {@link TabularData} output
     * generated by the reporter.
     *
     * @param reportData {@link TabularData} output generated by the reporter
     *
     * @return a {@link List} of service statistics
     */
    public SortedMap<Object, Data> getReporterData(TabularData   reportData,
                                                   VisualVMModel model);


    /**
     * Process a given {@link Object} array retrieved from a line in the
     * report and return a representation of this.<br>
     * Note: This may be available in a future Coherence release.
     *
     *
     * @param aoColumns {@link Object} array of column values
     * @param model     the {@link VisualVMModel} to use
     *
     * @return an instance of {@link Data}
     */
    public Data processReporterData(Object[]      aoColumns,
                                    VisualVMModel model);
}
