package com.oracle.coherence.patterns.eventdistribution.configuration;

import com.tangosol.coherence.config.ParameterMacroExpressionParser;
import com.tangosol.coherence.config.xml.CacheConfigNamespaceHandler;
import com.tangosol.config.xml.DocumentProcessor;
import com.tangosol.run.xml.XmlDocumentReference;
import com.tangosol.util.Base;

import java.util.List;


/**
 * This class has helper methods for CODI based unit tests.
 *
 * @author Paul Mackin  2013.07.18
 */
public class CodiTestHelper
    {
    /**
     * Process the XML using CODI.
     *
     * @param sXml     the xml to process
     *
     * @return  the object generated by CODI
     */
    protected static Object processXml(String sXml)
        {
        // configuration to process
        XmlDocumentReference docRef = new XmlDocumentReference(sXml);

        // create and configure the DocumentProcessor Dependencies
        DocumentProcessor.DefaultDependencies dependencies =
                new DocumentProcessor.DefaultDependencies(new CacheConfigNamespaceHandler());

        // finish configuring the dependencies
        dependencies.setClassLoader(Base.getContextClassLoader());
        dependencies.setExpressionParser(ParameterMacroExpressionParser.INSTANCE);

        // use a DocumentProcessor to create our CacheConfig
        DocumentProcessor processor = new DocumentProcessor(dependencies);
        return processor.process(docRef);
        }
    }
