package com.oracle.coherence.patterns.processing.config.builder;

import com.tangosol.coherence.config.ParameterMacroExpressionParser;
import com.tangosol.coherence.config.xml.CacheConfigNamespaceHandler;
import com.tangosol.config.xml.DocumentProcessor;
import com.tangosol.config.xml.NamespaceHandler;
import com.tangosol.run.xml.XmlDocumentReference;
import com.tangosol.util.Base;
import com.tangosol.util.SimpleResourceRegistry;

import java.util.List;

/**
 * This class has helper methods for ProcessingPattern CODI unit tests.
 *
 * @author pfm  2013.06.10
 */
public class CodiTestHelper
    {
    /**
     * Process the XML using CODI.
     *
     * @param sXml     the xml to process
     *
     * @return  the object generated by CODI
     */
    protected static Object processXml(String sXml)
        {
        // configuration to process
        XmlDocumentReference docRef = new XmlDocumentReference(sXml);

        // create and configure the DocumentProcessor Dependencies
        DocumentProcessor.DefaultDependencies dependencies =
                new DocumentProcessor.DefaultDependencies(new CacheConfigNamespaceHandler());

        dependencies.setResourceRegistry(new SimpleResourceRegistry());
        dependencies.setExpressionParser(new ParameterMacroExpressionParser());

        // finish configuring the dependencies
        dependencies.setClassLoader(Base.getContextClassLoader());
        dependencies.setExpressionParser(ParameterMacroExpressionParser.INSTANCE);

        // use a DocumentProcessor to create our CacheConfig
        DocumentProcessor processor = new DocumentProcessor(dependencies);

        return processor.process(docRef);
        }
    }
